### ISSUE TITLE
Path to gzip.txt issue

### ISSUE THREAD

**Issue by insamo** [gergo85/oc-backend-plus#11]
Hello! I have this error.

[2016-08-04 15:10:05] local.ERROR: Illuminate\Contracts\Filesystem\FileNotFoundException: File does not exist at path plugins/indikator/backend/assets/gzip.txt in /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php:40
Stack trace:
#0 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(215): Illuminate\Filesystem\Filesystem->get('plugins/indikat...')
#1 /home/vagrant/code/shedule/plugins/indikator/backend/Plugin.php(100): Illuminate\Support\Facades\Facade::__callStatic('get', Array)
#2 /home/vagrant/code/shedule/modules/system/Classes/PluginManager.php(261): Indikator\Backend\Plugin->boot()
#3 /home/vagrant/code/shedule/modules/system/Classes/PluginManager.php(243): System\Classes\PluginManager->bootPlugin(Object(Indikator\Backend\Plugin))
#4 /home/vagrant/code/shedule/modules/system/ServiceProvider.php(87): System\Classes\PluginManager->bootAll()
#5 [internal function]: System\ServiceProvider->boot()
#6 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#7 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(734): Illuminate\Container\Container->call(Array)
#8 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(717): Illuminate\Foundation\Application->bootProvider(Object(System\ServiceProvider))
#9 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation{closure}(Object(System\ServiceProvider), 21)
#10 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(718): array_walk(Array, Object(Closure))
#11 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#12 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(October\Rain\Foundation\Application))
#13 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(208): Illuminate\Foundation\Application->bootstrapWith(Array)
#14 /home/vagrant/code/shedule/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(105): Illuminate\Foundation\Console\Kernel->bootstrap()
#15 /home/vagrant/code/shedule/artisan(35): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#16 {main}

I think problem here

```
if ((bool)File::get('plugins/indikator/backend/assets/gzip.txt')) {
            ob_start('ob_gzhandler');
        }
```

My fix

```
if ((bool)File::get(base_path('plugins/indikator/backend/assets/gzip.txt'))) {
            ob_start('ob_gzhandler');
        }
```

**Comment by gergo85** [comment]
It is interesting. The File::get() and File::put() functions work properly for me and other plugins (Quick Edit) too.
Do you use the October in localhost or webserver? Is the Application URL (config/app.php) correct?

**Comment by insamo** [comment]
localhost(homestead), My app url stored in .env 

```
APP_URL=http://shedule.app
```

in config/app.php

```
'url' => env('APP_URL', 'http://shedule.app'),
```

Whoops :D

**Comment by insamo** [comment]
mb try...catch?)

**Comment by gergo85** [comment]
Perhaps it is a Laravel issue, because the File::get() function work properly in localhost and online server except Vagrant. Or not?

**Comment by insamo** [comment]
i check this on vps(no vagrant), issue repeat(. I check this issue on clear octobercms later...

**Comment by gergo85** [comment]
The OctoberCMS uses the same solution: https://github.com/octobercms/october/blob/master/modules/backend/models/BrandSetting.php#L111

So, I updated my plugins. Please download the Backend Plus on the Github and test it.

**Comment by insamo** [comment]
ok, thx it works!
