### ISSUE TITLE
Context Menu improvement

### ISSUE THREAD

**Issue by willvincent** [gergo85/oc-backend-plus#19]
The context menu is a really great feature, but it would be even better if it were to include links to other backend routes provided by plugins.  Seems to me, looking at the code that make it work, that you could probably scrape the page for the available menu items, rather than just being limited to the handful of hardcoded options.

**Comment by gergo85** [comment]
Thank you for your idea! I will improve the context menu, if I have enough time :)

**Comment by willvincent** [comment]
Likewise if I find time I'll rework the JS and submit a pull request ;)

**Comment by gergo85** [comment]
OK, thank you :)

**Comment by gergo85** [comment]
I did it! Please use the [Backend Elite plugin](http://octobercms.com/plugin/indikator-backendelite).
