### ISSUE TITLE
Assets for subdomain installed system

### ISSUE THREAD

**Issue by mahony0** [gergo85/oc-backend-plus#2]
https://github.com/gergo85/oc-backend-plus/blob/master/partials/_system_sidebar.htm#L31

L31 and L32 libraries include presuming system is installed on domain's home directory. I installed locally October CMS to /october dir for tests and keyboard not working because JS and CSS 404.

Is there any way for making this include depends on "config/app.php >> $url" variable?

Thanks.

**Comment by gergo85** [comment]
Thank you for advice. I modified the code. I hope the virtual keyboard will work properly on local server too.
