### ISSUE TITLE
Cache Widget

### ISSUE THREAD

**Issue by darki73** [gergo85/oc-backend-plus#20]
Clean install, getting the following message when trying to clear cache with the widget

> Обработчик AJAX не найден: 'onClearCache'.

In english

> AJAX Handler not found for: 'onClearCache'

**Comment by gergo85** [comment]
I know this issue. I am trying to solved this problem. The widget works properly in some cases.

**Comment by gergo85** [comment]
I fixed this issue. Please update the plugin.
