### ISSUE TITLE
Where did the list of objects for removal come from?

### ISSUE THREAD

**Issue by plyusninva** [gergo85/oc-backend-plus#22]
Hello!
1) Where did the list of objects for removal ("controllers / Trash.php") come from?
2) Why is the file included in this list? : https://github.com/gergo85/oc-backend-plus/blob/1d3118fb288f8dbf4c58c56f01cf91edcb58e3d2/controllers/Trash.php#L139

**Comment by gergo85** [comment]
Hello!

1. I collected it by manually.
2. It is only an example file.
