### ISSUE TITLE
Issue with october 3

### ISSUE THREAD

**Issue by inalto** [gergo85/oc-backend-plus#28]
Hello,
for everyone getting errors like this after October3 upgrade:

```
A syntax error was detected in /plugins/indikator/backend/updates/version.yaml. The string "!!! Updated for October 420+." could not be parsed as
  it uses an unsupported built-in tag at line 60 (near "1.6.6: !!! Updated for October 420+.") at line 43 (near "/vendor/october/rain/src/Parse/Yaml
  .php").

```
A simple fix is to remove the "!!!"  at line 60 on the file  /plugins/indikator/backend/updates/version.yaml

**Comment by gergo85** [comment]
Thank you for suggestion! I modified it and I update the plugin on the Market.
