### ISSUE TITLE
Hiding wrong icon when used in combination with Static Pages

### ISSUE THREAD

**Issue by jonwalstedt** [gergo85/oc-backend-plus#4]
When using Backend plus and setting it to hide the file manager it hides it correctly but when keeping this setting and then installing the plugin Static Pages it hides that link instead and file manager link reappears next to it. 

It uses the wrong css selector to hide the link #layout-mainmenu li:nth-child(3) since its not always the third link.

**Comment by gergo85** [comment]
Thank you for report the problem. I fixed this issue.
