### ISSUE TITLE
Menu Background Missing in Settings

### ISSUE THREAD

**Issue by abass** [gergo85/oc-backend-plus#5]
With the new updates in OctoberCMS, Backend Plus causes problems.

![IMG](https://camo.githubusercontent.com/8806e8fd04bca60ef110486b808225be7d6433f1/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f662e636c2e6c792f6974656d732f324b304b335a315a30593071316b3339327430782f496d616765253230323031362d30352d31372532306174253230382e31352e3533253230504d2e706e673f763d6461373730373233)

Please refer to this issue on OctoberCMS where we discuss it:

https://github.com/octobercms/october/issues/2023

**Comment by gergo85** [comment]
As soon as, I will update the plugin for OctoberCMS stable version.

**Comment by gergo85** [comment]
I have started to develop the next version of Backend Plus. You can find it on the Github. For now it is a beta version.

**Comment by abass** [comment]
Great, thank you!

On Tue, Jun 14, 2016, 7:34 AM Szabó Gergő notifications@github.com wrote:

> I have started to develop the next version of Backend Plus. You can find
> it on the Github. For now it is a beta version.
> 
> —
> You are receiving this because you authored the thread.
> 
> Reply to this email directly, view it on GitHub
> https://github.com/gergo85/oc-backend-plus/issues/5#issuecomment-225854869,
> or mute the thread
> https://github.com/notifications/unsubscribe/AFQDyqpl-Fq53w79XKlPH6CR03cKoICaks5qLpHcgaJpZM4Ij0oy
> .
> 
> ## 

Alex Bass

President & Co-Founder, CyberBytes Inc.
cyberbytesinc.com // @alexhbass

**Comment by gergo85** [comment]
The new version of plugin is available on the OC Marketplace too.
