### ISSUE TITLE
Error in Dashboard Widget.

### ISSUE THREAD

**Issue by mokeev1995** [gergo85/oc-backend-plus#9]
![image](https://cloud.githubusercontent.com/assets/8450876/16710894/2486fd26-4649-11e6-9f2d-9fbce057911b.png)

![image](https://cloud.githubusercontent.com/assets/8450876/16710893/1631b87e-4649-11e6-90a4-ceaba93072a5.png)

**Comment by sander-beenen** [comment]
Fixed by changing MaintenanceSettings on line 6 and 62 in \Indikator\Backend\ReportWidgets\Status.php to MaintenanceSetting.

**Comment by mokeev1995** [comment]
#10
